### ISSUE TITLE
recoloring the balls

### ISSUE THREAD

**Issue by midosgithub** [Flutterish/Hitokori#19]
i have no idea if this would be easy to implement but id love to see a option to change the color of each ball

**Comment by Flutterish** [comment]
I think it would be incredibly easy as long as i can make a color picker since osu does not offer one.
I do not want to use RGB sliders but a HSL box like this:
![hsl box](https://user-images.githubusercontent.com/40297338/108272895-245a2f80-7173-11eb-9e19-ee0c936a8cd3.png)
Actually on second though, I think this can be done with skinning, but I don't know how to implement skins yet.
One problem that changing their colours would pose is that with "flashlight", the firey one glows and with customizable colors it would not really make sense.

**Comment by Flutterish** [comment]
This is the current progress by the way:
![obraz](https://user-images.githubusercontent.com/40297338/109355736-f6b26c00-787f-11eb-8b5e-fc99bd37541b.png)
I'm working on making it look better / more in line with osu, some final UX decisions and I'll be ready to publish in the next release.
