### ISSUE TITLE
Change orbit ring

### ISSUE THREAD

**Issue by KingBranBran** [Flutterish/Hitokori#8]
I think it may be more readable if you made the orbit ring a little less brighter. Maybe even make the ring itself dotted.

**Comment by Flutterish** [comment]
I like the idea of it being dotted or dashed, but Im not sure how it would work when it shrinks and expands. Would the dash-marks always be the same length or not, would they dissapear as the ring contracts and if so, how exactly?

Would [this be acceptable?](https://streamable.com/q20wnt)

**Comment by KingBranBran** [comment]
I think the simulation looks pretty good!

Maybe another way that it could contract/grow is by adjusting the length of the dashes. But that will mean the number of dashes will remain constant.

I think the one you showed looks cool.

**Comment by Flutterish** [comment]
[Like this?](https://streamable.com/t6edkt)

**Comment by KingBranBran** [comment]
Yes that's exactly what I was thinking

**Comment by Flutterish** [comment]
Then I believe the best solution would be to add a setting for dash-style ( solid, dashed[default] or dotted ) and probalby one for opacity, which by default would be lower than the current one. I prefer the constant dash amout because on the other one the "expanding area" moves way faster than the opposite side. Im not sure if it will look good, but I might make it rotate slightly, too.

**Comment by KingBranBran** [comment]
Ok, sounds good!

**Comment by Flutterish** [comment]
Implemented in 0.13
